### ISSUE TITLE
Cannot use two select interactions at the same time

### ISSUE THREAD

**Issue by elemoine** [openlayers/ol3#1988]
Currently one cannot use two Select interactions at the same time. The last Select interaction added to the map would always stop the "single" click event, making it invisible to the second Select interaction.

See https://github.com/openlayers/ol3/blob/master/src/ol/interaction/selectinteraction.js#L176. The return value should probably be configurable.

**Comment by simonseyock** [comment]
Just an unqualified comment:

I think it would be useful to be able to add two select interactions to the map.

It would be possible to easily specify different actions for different filter functions and different actions for different conditions (i.e. pointerMove, singleClick). And having interactions with the multi-option on or off would be nice, too.

**Comment by simonseyock** [comment]
Again i am having problems with not being able to have to select interactions with the same eventtype.

Differing from what i stated above it is possible to have two select interactions with different eventypes, though.

The thing is: I have two different modules in the software which i would like to manage an own select interaction. That is not possible at the moment. A solution for this is of course to manage an interaction somewhere and use it with both modules. But this differs very much from handling same interactions with different eventtypes (for example one select for hover and one for click) and even more from handling different interaction with the same eventtype (for example a select with eventtype 'click' and a draw interaction). The first case will work nicely with having two select interactions with different conditions and the second case would work with deactivating one interaction and activating the other.

what i really would like to do is adding two interactions with different filter functions instead of having to use the same interaction for different purposes.

i made a little fiddle, btw:

https://jsfiddle.net/simon_seyock/qmws0nxw/7/

**Comment by ahocevar** [comment]
See #4882, which has a good discussion for possible solutions to this issue.

Closing this as duplicate.

**Comment by lucas-issa** [comment]
I had a similar problem and I fixed creating a Collection for the "ol.interaction.Select" that does not duplicate features. It has been fixed because "ol.interaction.Select" uses an "ol.source.Vector" that does not duplicate features. 

In my case I was using two select interactions and some times when I was selecting features too fast an error was happening. It was happening because the same feature was added more than once in the features Collection and in the "ol.source.Vector" of the "ol.interaction.Select".

I'm adding this comment because it can help someone.

Here is an example code:

```javascript
// ...

let select1 = new ol.interaction.Select({
	features: createUniqueElementsCollection(),
	// ...
});

let select2 = new ol.interaction.Select({
	features: createUniqueElementsCollection(),
	// ...
});

select1.on('select', select1Handler);
select2.on('select', select2Handler);


map.addInteraction(select1);
map.addInteraction(select2);


let select1Handler = (e) => {
	// ...
};
let select2Handler = (e) => {
	// ...
};

/** 
 * Collection that do not duplicate elements. Duplication check is make by element.getId().
 */
let createUniqueElementsCollection = () => {

	let c = new ol.Collection();
	c.insertAt__original = c.insertAt.bind(c);
	c.insertAt = (index, element) => {
		let included = false;
		c.forEach((aElement) => {
			if (aElement.getId() == element.getId()) {
				included = true;
				return;
			}
		});

		if (!incluido) {
			return c.insertAt__original(index, element);
		} else {
			return false;
		}
	};
	return c;
};

```

**Comment by michalzielanski** [comment]
A hook for those who need multiple select interactions:

```js
var selectInteraction, originalHandleEvent;
selectInteraction = new ol.interaction.Select({
    // ...
});

originalHandleEvent = selectInteraction.handleEvent;
selectInteraction.handleEvent = function(mapBrowserEvent) {
    originalHandleEvent.apply(this, arguments);

    // true, not to stop event propagation.
    return true;
};
```
