### ISSUE TITLE
Api docs: broken link for ol.Feature

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#2149]
The 'vector features' link on the current docs [landing page](http://ol3js.org/en/master/apidoc/index.html) is broken: it points to ol.Feature.html but this has been generated as ol.Feature_.html. ol.feature.html is fine.
This is rather strange, as on the docs I've just generated on my own machine, it is ol.feature_.html and ol.Feature.html

From a quick look at apidocs/ I can't see where this '_' is being generated. Is it something to do with case-insensitivity, having both ol.feature and ol.Feature?

**Comment by bartvde** [comment]
okay this is still an issue currently in the api docs

**Comment by tschaub** [comment]
> okay this is still an issue currently in the api docs

Confused.  The [doc index for master](http://openlayers.org/en/master/apidoc/) links to http://openlayers.org/en/master/apidoc/ol.Feature.html which is not a 404.

**Comment by tschaub** [comment]
I see http://openlayers.org/en/v3.4.0/apidoc/ol.Feature_.html.  So we need to determine where the `_` is getting added and how to consistently make that not happen.  It could be that someone is building with an old JSDoc version.

**Comment by probins** [comment]
I don't think so, Tim. I think it's inherent in JSDoc. Whether it's `feature` or `Feature` that gets an _ is essentially random, so it may work one time and not the next.

**Comment by tschaub** [comment]
239a90cd557abd47b6e28befe37b028242dcdd5a ugh (the name `ol.feature.FeatureStyleFunction` is bad in many ways)

**Comment by ahocevar** [comment]
It's just a typedef - as long as we don't change the signature of the function, we don't break the API.

**Comment by tschaub** [comment]
It is probably not right to call #3602 a "fix" for this issue, because it doesn't fix broken links in any previous release docs.  The [API doc index](http://openlayers.org/en/v3.4.0/apidoc/) for the v3.4.0 release (and perhaps others) has a bad link for the `ol.Feature` docs.  This cannot be fixed by editing the [source for this page](https://github.com/openlayers/ol3/blob/v3.4.0/config/jsdoc/api/index.md) without deleting the tag and creating a new one (which I don't think is warranted).

The docs for the next release won't have this problem.  And we can avoid the problem in the future by never creating a "namespace" that is the same as an existing symbol (minus the case).

Unfortunately, we have this problem lurking with `ol.Size` and the `ol.size` namespace.  It was just [made exportable](ddf5e48830ddca8b97154365c518b3ae726b83e1) and the next step is typically that someone adds a corresponding `.jsdoc` file.  Then we'll have broken links for anybody who assumed that `ol.Size.html` was a stable URL.
