### ISSUE TITLE
Dynamic overlay positioning ("keep popup in map")

### ISSUE THREAD

**Issue by nidico** [openlayers/ol3#2181]
It'd be useful if overlays would open in a direction which keeps them within the currently shown map viewport. I think this corresponds to the [keepInMap property in OL2](http://dev.openlayers.org/docs/files/OpenLayers/Popup-js.html#OpenLayers.Popup.keepInMap). This is in particular relevant as long as #2180 isn't possible.

A possible sketch would be:

- The map is divided in compartments which define in which direction the popup open; e.g. if the referred element is in the top-left compartment, the map would open towards the bottom-right. There might be 1 to 3 compartment in each dimension. (There's different ways to do this, but this sounds relatively simple to me)
- Allow to set `automatic` as possible [`ol.OverlayPositioning`](http://ol3js.org/en/master/apidoc/ol.html#OverlayPositioning).
- Allow to define number of overlay positioning compartments (1-3) per dimension. Default to `x=3`, `y=2`.
- If the overlay is opened, a class (or two, one for each dimension) is set, depending on the chosen positioning, in order to choose the right bubble / offset etc. (I hope this is doable in pure CSS).

Does that make sense? Are there already other plans for this? Would you interested in a Pull Request with the above proposal?

**Comment by bartvde** [comment]
We now have autoPan with #3256

**Comment by pranjalrathod01** [comment]
by using autopan we force the underlying map to move, is there any way pop should auto adjust its location. (like windows right click menu )(Because at the topmost corners of the map,where there is not enough space for popup to stay on maps, popups gets outside the maps.)

**Comment by intotecho** [comment]
I enabled autoPan , but the users logged it as a bug! They really disliked it.

1. User places mouse/pointer to hover over a feature
2. Hover causes a popup to display, but it's clipped - partially outside view so unreadable
3. View pans until Popup is now inside view 
BUT User's pointer is no longer over the target feature. So the popup disappears (hover exit event) 
User has to chase the feature again to see the window.

A suggested solution would be for autoPan (or some other option) to move the popup window instead of pan the base view.

**Comment by intotecho** [comment]
Something like this [fiddle](http://jsfiddle.net/bunjil/L6rztwj8/52/). 
Its a poorly implemented reversal of ol.Overlay.[panIntoView()](https://github.com/openlayers/openlayers/blob/d8efa569d9d6722c4fa653b9e1891799a7c58245/src/ol/Overlay.js). 
The real use case if for hover over features near the edge of the map.
