### ISSUE TITLE
Select interaction ignores layer filter for feature overlays

### ISSUE THREAD

**Issue by ssaarela** [openlayers/ol3#2940]
Map.forEachFeatureAtPixel is called for all features of a feature overlay regardless of layer filter. I have a couple of layers containing different kind of editable information and use Draw (polygons) for one and Select/Modify (points) for another. I try to target Select to the layer containing the relevant points with layers option, but as Draw uses feature overlay, Select grabs those polygons immediately. 

Would it be possible to use layerFilter also in the function(feature, layer) -argument of the map.forEachFeatureAtPixel? One can always supply a filter that accepts null-layer, but without it I see no way to skip feature overlays.

**Comment by pgiraud** [comment]
I've written an example that may illustrate the issue.
http://jsfiddle.net/pgiraud/axmbruf5/

In this example, we have two layers that are "unmanaged". The select interaction is configured with a `layers` option which should limit the selection to only one layers. However, one is able to select any of the 2 points.

**Comment by pgiraud** [comment]
In the tests (https://github.com/openlayers/ol3/blob/master/test/spec/ol/renderer/canvas/canvasmaprenderer.test.js#L49), it's clearly written that forEachFeatureAtPixel will always return features from the unmanaged layers.

1 - It should be documented in the API doc.
2 - Can someone explain this choice?

**Comment by elemoine** [comment]
https://github.com/openlayers/ol3/pull/3883 and https://github.com/openlayers/ol3/issues/3878 are relevant.

And `ol.layer.Layer#setMap` includes docs about this already. See https://github.com/openlayers/ol3/blob/master/src/ol/layer/layer.js#L150-L161.

**Comment by pgiraud** [comment]
OK. Thanks.

**Comment by elemoine** [comment]
@pgiraud So I guess the problem is related to the Select interaction itself using an unmanaged layer for drawing selected features. If that unmanaged layer is filtered out then the selected features won't be returned by `forEachFeatureAtPixel`, making it impossible to unselect them. But there may be a better way to handle this. Instead of ignoring the layer filter for unmanaged layers we could make the Select interaction combine the user-provided layer filter with its own layer filter, in an OR operation.

**Comment by elemoine** [comment]
See https://github.com/openlayers/ol3/pull/4143.
