### ISSUE TITLE
BBOX of GetMap request is bigger than layer extent

### ISSUE THREAD

**Issue by Martin-Wegner** [openlayers/ol3#3131]
If you have a complete world map (zoom is 4) and for example a TileWMS with an [6, 47, 15, 55] extent, then the BBOX of the GetMap request will be [0, 45, 22.5, 67.5].

In general the question is why OpenLayers does not take the extent into account while building GetMap requests? The current behaviour decreases the performance because more data will be queried from the geo database and more points must be rendered by the geo server.

The current behaviour makes it impossible to implement the workaround of a current Geoserver bug https://jira.codehaus.org/browse/GEOS-6831 :(

See also issue https://github.com/openlayers/ol3/issues/2787 and jsfiddle http://jsfiddle.net/tfwyzmw1/1/

**Comment by ahocevar** [comment]
In this case it is not enough to set the extent of the layer, which only limits the rendered extent. You will have to configure a custom tilegrid for your TileWMS source if you want to limit the extent that is requested from the server.

I'm closing this issue, because it does not appear to be a bug. Feel free to reopen if there is a bug.

**Comment by Martin-Wegner** [comment]
OK, can you please give me an example TileGrid for my example above?
I don't understand how predefined resolutions and tiles sizes can exactly control the resulting BBOX :(

**Comment by ahocevar** [comment]
It is the nature of tile layers that tiles are in a regular grid. If you need an exact extent, you should consider using `ol.layer.Image` and `ol.source.ImageWMS`. If you want to stick with tiles, your custom tilegrid configuration would look like this: http://jsfiddle.net/9bLytpt7/1/. But note that tiles here will still exceed your extents, because tiles will not be clipped and always fill the complete `tileSize`.
