### ISSUE TITLE
examples/example-list.html is missing

### ISSUE THREAD

**Issue by daveheitzman** [openlayers/ol3#3234]
Attempting to check out examples/index.html locally. 

I get a partially complete page with an error that example-list.js is missing.

It would be nice to be able to play with these locally.

**Comment by daveheitzman** [comment]
It works in the main release, just not in the 'source'

**Comment by tschaub** [comment]
The example index is generated as part of a build step, and we aren't keeping build artifacts in the repository.  In the next few months, I hope to make it so our examples are built from a template instead of the current situation of copy/pasting a ton of markup whenever a new example is created.  This will make it even clearer that a build step is required when checking out the repository.  As you noticed, in the release archives we include build artifacts (like the example list).

To get started from a clone of the repository, you need to have [Node](http://nodejs.org/) installed.  These two steps will install the development dependencies, build the example index, and start a development server for running examples and tests:

```
npm install
npm start
```
