### ISSUE TITLE
Strange Images

### ISSUE THREAD

**Issue by 1Map** [openlayers/ol3#3290]
I have a map with only 1 wms layer.  When I zoom in all works, but the moment I zoom out to see the complete extent, it leaves ghost images (Only in the area outside the layer extent - ie. where there are no tiles).  I think the reason for this is that it does not clear the map after a zoom where there are no tiles (Outside the layer extent).

See screenshot:

WRONG
![image](https://cloud.githubusercontent.com/assets/1152458/6413963/d5f7d656-be9c-11e4-9e46-82e147d81991.png)

CORRECT
![image](https://cloud.githubusercontent.com/assets/1152458/6414567/130bcd50-bea1-11e4-926a-d258c281d980.png)

**Comment by elemoine** [comment]
This is very bad. What renderer do you use? Do you want the jsfiddle reproducing the problem?

**Comment by 1Map** [comment]
I use canvas renderer.  I will try and reproduce the problem on jsfiddle and will send you the link.

**Comment by 1Map** [comment]
Here is a JSFiddle showing the problem

http://jsfiddle.net/xc8r0w2o/18/

**Comment by elemoine** [comment]
Thank you for the test case. I created a branch reproducing the problem in the `wms-tiled` example: https://github.com/elemoine/ol3/commit/3290. I don't know what the problem is right now.

**Comment by elemoine** [comment]
Result of my git-bisecting:

```
$ g bisect bad                                                                                                
50c0bc6879d38f2a6da0057b919069d6ad3bfb12 is the first bad commit
commit 50c0bc6879d38f2a6da0057b919069d6ad3bfb12
Author: Tim Schaub <tim.schaub@gmail.com>
Date:   Tue Nov 11 08:54:10 2014 -0800

    Clip rendering to layer extent

:040000 040000 0d1bb3dbfa937b3deef6becf8b9be33540969555 c0257ee997a72e81a36dc2143ae0fd47104cdcdc M      src
```

**Comment by tschaub** [comment]
I'm curious if this could have to do with the `ol.TileState.EMPTY` handling in the canvas tile layer renderer.

**Comment by ahocevar** [comment]
I tried a few things now. I removed all elements from the tile queue, cleared the vector source, but both to no avail.

**Comment by ahocevar** [comment]
Sorry, wrong ticket.

**Comment by ahocevar** [comment]
Looking into this now.

**Comment by ahocevar** [comment]
Here is the result of my research: this issue is caused by the WMS server in the example returning transparent PNG images for tiles outside the projection world bounds. With `TRANSPARENT` set to `false`, OpenLayers thinks that it does not have to clear tiles (due to the `opaque` option that is set on the parent of the TileWMS source, which is an optimization). This of course does not work when tiles are advertised as opaque, but are in fact transparent.

In this specific case, the solution is to remove the `TRANSPARENT` attribute of the WMS params.

I think we can we close the issue. Do @elemoine and @1Map agree? Alternatively, we can expose the `opaque` option to `olx.source.TileWMSOptions`, but I think that would cause confusion because people would then have to care about both the `TRANSPARENT` param and the `opaque` option.

**Comment by elemoine** [comment]
Woa! Good work Andreas! I agree that we can close the issue.

**Comment by 1Map** [comment]
Thanks for the help, problem was indeed that it was suppose to be TRANSPARENT: true.

I am closing this one for now
