### ISSUE TITLE
Something wrong with closure-util

### ISSUE THREAD

**Issue by liuxiaoer** [openlayers/ol3#3546]
I used the command :npm install openlayers from the [tutorial] (https://github.com/openlayers/ol3) to install openlayers. Then  compiled my application with the [tutorial] (https://github.com/openlayers/ol3/blob/master/doc/tutorials/closure.md), but i coundn't find the command of build.

I found the version of the closuer-util I installed is 1.3.0. I guess the reason of the problem is the wrong version. So what should I do to build my application with ol3 and closure-util.

**Comment by elemoine** [comment]
OpenLayers 3.4.0 depends on closure-util 1.3.0 which does not have the `build` command. The tutorial will work with OpenLayers 3.5.0, which will be released  beginning of May.

**Comment by liuxiaoer** [comment]
how can I build my application with OpenLayers3.4.0 and closure-util 1.3.0

**Comment by elemoine** [comment]
You can try to add `"closure-util": "1.4.0"` as a dependency in your application's `package.json`, and then you'd use `./node_modules/.bin/closure-util` instead of `./node_modules/openlayers/node_modules/.bin/closure-util`. You may also need a `closure-util.json` file that is the same as [that](https://github.com/openlayers/ol3/blob/v3.4.0/closure-util.json) of ol3 v3.4.0. I haven't tried this myself, but it may work.

**Comment by liuxiaoer** [comment]
Thanks for your help.
