### ISSUE TITLE
ol.interactions.Select without highlight Style

### ISSUE THREAD

**Issue by FreeGIS** [openlayers/ol3#3607]
var selectClick = new ol.interaction.Select({
            condition: ol.events.condition.click
        });
        map.addInteraction(selectClick);
        //点击  气泡，显示气泡对应信息
        selectClick.on('select', function(e) {
            showPopup(e.selected[0]);
        });
 function showPopup(feature) {
            if(feature==undefined)
            {
                closePopup();
                return;
            }
            selectFeature=feature;
            selectClick.featureOverlay_.removeFeature(feature);
            selectFeature.setStyle(iconSelectStyle);
           // vectorLayer.getSource().removeFeature(feature);
            var geom = feature.getGeometry();
            var coordinate =geom.flatCoordinates;
            content.innerHTML =  '<h3>'+selectFeature.getProperties().title+'</h3></br><code>' + selectFeature.getProperties().info + '</code>';
            overlay.setPosition(coordinate);
        }

when i select a feature i find the feature have a default style,when i use setStyle(),i find there is noting change.finally,i read souce code,i find the style by select feature is a featureOverlay,i has to use "selectClick.featureOverlay_.removeFeature(feature);" to  solve it.  i hope have a good idea to remove or change the featureoverlay.

**Comment by tsauerwein** [comment]
@FreeGIS [ol.interaction.Select](http://openlayers.org/en/master/apidoc/ol.interaction.Select.html) takes a `style` argument that you can use to change the style of selected features. I am not sure about your use-case, but maybe the select interaction is not the best option. Maybe this [example](http://openlayers.org/en/master/examples/icon.html) is more what you want to do.

In the future please ask questions on [StackOverflow](http://stackoverflow.com/questions/tagged/openlayers-3).

**Comment by kobbe** [comment]
@tsauerwein I would like this exact functionality. Setting the style to null in order for the selector not to change the style.

In this way I will get the benefits of the selector while keeping the style function on the layer. Today if I want to have the style function on the layer I basically have to implement the selector manually with map.on('click'. 

The reason for using a style function instead of using two separate (one in the selector and one in the layer) is because using one is easier and less code. 

(I can have the style on each feature insted of on the layer and that is currently my workaround. But It would be better to just set the style on the layer)

**Comment by chinchillaLiao** [comment]
![image](https://user-images.githubusercontent.com/26104317/130305477-42d58c30-87ae-4f9f-a420-bc305b6af968.png)

when I try to set style to null, my typescript got a error.
