### ISSUE TITLE
ol.control.Zoom doesn't zoomOut when delta is 0.5

### ISSUE THREAD

**Issue by Tobino** [openlayers/ol3#3684]
Hi

I've got 2 problems with delta=0.5
http://plnkr.co/edit/OCy0Ru3b937JRmlyIsBO?p=preview

When I zoom out with control Zoom the current zoom don't change.

I can avoid this problem with delta=0.6. But is there a way to get current zoom with method getZoom?
or even approximate zoom, like 2 or 2.6?

**Comment by alvinlindstam** [comment]
The documentation for View.getZoom says 'Get the current zoom level. Return undefined if the current resolution is undefined or not a "constrained resolution".' (http://openlayers.org/en/v3.5.0/apidoc/ol.View.html#getZoom)

Each zoom level is actually nothing more than a specific (constrained) resolution, and I would say that they are only meaningful as enumerations and not as a continuous value. Each zoom level is a step and should be used by stepper controls such as ol.control.Zoom.

The list of zoom levels is basically a predefined or generated list of resolutions, which does not have to be equally or regularly spaced. The default (used in your example) is that each zoom level has half the resolution of the previous, but that could be changed by the user. The problem comes when defining what zoom level 2.5 actually means. Is it the resolution right in between the resolution of zoom level 2 and 3. Or is it the result of the same exponential function potentially used for creating the zoom level?

You would probably be better off by using integer zoom levels in the control, and instead defining smaller differences between each zoom level (using the "resolutions" or "zoomFactor" View options).

However, as long as you don't define custom resolutions, a floating point zoom level could be calculated as Math.log2(maxResolution / currentResolution). This assumes the default zoomFactor of 2, if you define another you have to use another logarithm base. I have edited your example to do this: http://plnkr.co/edit/DfLlZQnZGfrz9f4reAwe?p=preview

The example however shows that when using ol.control.Zoom and delta=0.5, the control does not move 0.5 zoom levels each time. When zooming in from 2, you get 2.5, 3.5, 4.5... and zooming out doesn't work. Should it handle floating point deltas more correctly, or respect the views constraints? Should it accept non-integer deltas as options, and should we update http://openlayers.org/en/v3.5.0/apidoc/ol.control.Zoom.html to inform of suitable values?

**Comment by Tobino** [comment]
Thank you for the answer.

The best solution for me, was to use integer zoom levels and change "zoomFactor" View options.
