### ISSUE TITLE
Tap event sensitivity on tablet

### ISSUE THREAD

**Issue by pgiraud** [openlayers/ol3#3724]
Using a Samsung Galaxy Tab S 10.5, the drawing tools don't behave as expecting. The user needs to touch the screen for a small amount of time before a point is added to the map. A short press doesn't have any effect. With a too long press, the system (android) wants to do copy/paste.

This video shows the problems: https://www.youtube.com/watch?v=dY4ng8BjE14

@petzlux can you please tell us which version of Chrome is installed on this tablet?

**Comment by petzlux** [comment]
Its Chrome 42.0.2311.111 on Android 5.0.2

**Comment by fredj** [comment]
I've the same kind on issues with a [Samsung Galaxy Tab 4 10.1](http://www.samsung.com/us/mobile/galaxy-tab/SM-T530NZWAXAR) and Chrome 42.0.2311.111.

http://openlayers.org/en/master/examples/measure.html

**Comment by fredj** [comment]
The position between a down and a up event is quite big on this device and [the distance test](https://github.com/openlayers/ol3/blob/master/src/ol/interaction/drawinteraction.js#L390) often fails.

**Comment by fredj** [comment]
@petzlux please test http://fredj.io/ol/click-tolerance/examples/measure.html
The click tolerance is 6px (2px in [master](https://github.com/openlayers/ol3/blob/master/src/ol/interaction/drawinteraction.js#L266))

**Comment by petzlux** [comment]
@fredj  Super, works much much better !

**Comment by elemoine** [comment]
Same issue here on my Android Phone with Chrome 43.0.2357.78.

**Comment by elemoine** [comment]
> Same issue here on my Android Phone with Chrome 43.0.2357.78.

Actually it might not be as bad on my phone. I do get pointerdown/pointerup sequences that don't draw a point, but I still can draw a complete geometry without too much trouble.

But the user experience is definitely better when using a click tolerance of 6px (as in @fredj's click-tolerance branch) rather than 2px (master).

What I would like to do is to add a `clickTolerance` option to the Draw interaction. We can mark it as experimental for now, but we can play with it in applications to try to figure out what could be a good value.
