### ISSUE TITLE
Modify interaction and Circle geometry

### ISSUE THREAD

**Issue by yoan-m** [openlayers/ol3#3777]
Hello,

How can I edit a feature with a Circle geometry ?
ol.interaction.Modify doesn't work with ol.geom.Circle.

Thanks

**Comment by nojinkokkatt** [comment]
Hello
 Are you got solution ?. I have same issue , 
Thanks

**Comment by yoan-m** [comment]
No sorry, still waiting.

**Comment by jonataswalker** [comment]
I guess this is because user questions should be made [here](http://stackoverflow.com/questions/tagged/openlayers-3).

**Comment by elemoine** [comment]
The modify interaction doesn't currently support modifying circles.

**Comment by matthiasdailey-ccri** [comment]
@elemoine , if someone were to write custom code for a modify interaction supporting circles, would that be possible?

I assume this feature doesn't exist in OpenLayers yet because it wasn't high priority, or because no one has gotten around to it. But I wanted to check: has anyone attempted to add this feature and found that there were challenges or technical hurdles that would make it hard or impossible to code this feature?

**Comment by bartvde** [comment]
@matthiasdailey-ccri I don't think it was attempted as yet. Your assumptions (not high priority, no one has gotten round to it) are probably right.

**Comment by bartvde** [comment]
see also: https://github.com/openlayers/ol3/issues/5510

**Comment by trinity0091** [comment]
Is there any solution for it    " Modify Circle geometry".
The problem still existing in ol3_v4.0.1.?


https://codepen.io/trinity0091/pen/XpGNgG?editors=0010

**Comment by ahocevar** [comment]
Circle modification is now available. See http://openlayers.org/en/latest/examples/draw-and-modify-features.html. It was implemented with #6457.
