### ISSUE TITLE
Infinite vector layer reload when ol.source.Vector.clear() is called.

### ISSUE THREAD

**Issue by Blackhex** [openlayers/ol3#3812]
Consider the following example in OpenLayers 3.6.0:

    var geoJsonFormat = new ol.format.GeoJSON();
    var vectorSource = null;
    
    function loaderFunction(extent, resolution, projection) {
      var from = ol.proj.transform([extent[0], extent[1]], 'EPSG:3857', 'EPSG:4326');
      var to = ol.proj.transform([extent[2], extent[3]], 'EPSG:3857', 'EPSG:4326');
      var url = "http://example.com/test?bounds=" + from.concat(to).join(',');
      jQuery.ajax({
        url: url,
        success: function (data) {
          var features = geoJsonFormat.readFeatures(data, {
            dataProjection: 'EPSG:4326',
            featureProjection: 'EPSG:3857'
          });
          vectorSource.clear(true);
          vectorSource.addFeatures(features);
        }
      });
    }
    
    vectorSource = new ol.source.Vector({
      format: geoJsonFormat,
      loader: loaderFunction,
      projection: 'EPSG:4326',
      strategy: ol.loadingstrategy.bbox
    });
    
    var map = new ol.Map({
      target: 'map',
      layers: [
        new ol.layer.Tile({
          source: new ol.source.OSM()
        }),
        new ol.layer.Vector({
          source: vectorSource
        })
      ]
    });

When the `loaderFunction()` success callback contains line `vectorSource.clear(true);` regardless if the paremeter is `true` or `false`, the layer is infinitely reloading even when the camera position and zoom is not changing. When this line is removed the infinite reload is not looping but obvisously the features are multiplying in the layer.

**Comment by WiteCastle** [comment]
I have this exact same problem. vectorSource.clear(true) is the only way I could find to stop the features from multiplying but it's unusable.

**Comment by WiteCastle** [comment]
Here's a [jsfiddle](https://jsfiddle.net/ebsanu/vtmnqbcd/3/) using a modified example with `vectorSource.clear(true)`.

**Comment by alvinlindstam** [comment]
When you say "multiplying" (when not using source.clear), do you mean that each feature may be included mutliple times in the source or that the total amount of features keeps increasing as new areas are loaded?

ol.source.Vector does not add duplicates of the same features if they have the same ID: https://github.com/openlayers/ol3/blob/master/test/spec/ol/source/vectorsource.test.js#L391

Your example, @WiteCastle, has ID's defined, so panning and loading duplicates will not cause duplicates to be kept in the source. I don't know about your source, @Blackhex, but adding unique ID's might solve your issue.


The source keeps track of extents that has been loaded, in order to only load new extents. This is done at request time. At response time, your loader function calls clear, which also clears the collection of loaded extents. So next time the maps checks if it should load a given extent, it sees that nothing is loaded and reloads. Calling clear will always cause the source to reload.

I see a few possible options (from a library perspective):
* Improve documentation for ol.source.Vector.clear. It is currently documented that it removes all features, but not that it also clears the information about loaded extents. The current documentation might suggest that it is equal to calling removeFeature for all features, which it is not.
* Expose the loaded extents to the user, so that you could manually add an extent to be considered loaded or remove some features and mark an extent as unloaded. Slightly related to https://github.com/openlayers/ol3/pull/3876

**Comment by Blackhex** [comment]
I was testing this with a GeoJSON source with  abounding box filtering when the bounding box was far larger than the dataset extent. In that case the feature count was exactly 2x, 3x, etc. multiply of the features count in the layer each time. I'll try to add unique IDs...

**Comment by ahocevar** [comment]
You should not be calling `ol.source.Vector#clear();` in the loader function. Also note that `bbox` and `tile` strategies will only work properly if features read from the source have a unique id (`id` property in GeoJSON features) set.

I am closing this issue as WORKSFORME.

**Comment by Bear4** [comment]
Could You precisize what does it mean:  _"...if features read from the source have a unique id (id property in GeoJSON features) set."_
I have JSONP output:
parseResponse({"type":"FeatureCollection","totalFeatures":8,"features":[{
"type":"Feature",
**"id":"v_wezel_rfid.fid--7639626f_157e2081c19_-635",**
"geometry":{"type":"Point","coordinates":[2574930.2961,7008849.673]},
"geometry_name":"geom",
"properties":{
**"id":8825,**
"adr_adm":"Bro 7",
"door_action":13,
"last_read_timeout":72,
"bbox":[2574930.2961,7008849.673,2574930.2961,7008849.673]}}, ... }]

**First id** is generated by GeoServer 
and have unique number for all request, 
e.g. the same features but 
call 1-st time has:   v_wezel_rfid.fid--7639626f_157e20d7f29_8a6
call 2-nd time has:  v_wezel_rfid.fid--7639626f_157e20d7f29_116a	
call 3-rd time has:   v_wezel_rfid.fid--7639626f_157e20d7f29_13cd
and so on...

**The second id** has unique number that don't changes for next request , still the same.

And OL-3 v 3.18.2 when use loader strategy: ol.loadingstrategy.box duplicate the feature despite having one static id and unfortunately one changing id (by GeoServer).

Solution for me till now is static : 
strategy: function() { return [ [2553624.5, 6988200.5, 2602467.0, 7022520.0] ]; }

I will be grateful for clarification the **unique id**.

**Comment by ahocevar** [comment]
This looks like your GeoServer layer does not have an id field configured. You'll have to fix this on the GeoServer side. Once it's fixed, your ids will look like `'v_wezel_rfid.1234'` rather than `'v_wezel_rfid.fid--7639626f_157e20d7f29_13cd'`, and will be unique across requests.

**Comment by Bear4** [comment]
Thanks for response I'll look at that.

**Comment by Pesonet1** [comment]
For me this was fixed by making sure that the option "Expose primary keys" was set on inside the vector source options. After this, ids were in the correct form as @ahocevar stated.
