### ISSUE TITLE
multiple tile layers memory problems and crash in OL3JS map

### ISSUE THREAD

**Issue by TomasHorvath** [openlayers/ol3#3816]
We have a map application build on Ol3JS which displays several overlaying tile layers. When user pans and zooms in IE11, the browser memory consuption increases very fast and whole story ends up in JS error in OL3 lib corresponding to insufficient memory.

This is our sample code, which can reproduce the error with OSM tile layer (normally, we use our internal tile sources instead of OSM):

https://jsfiddle.net/xpLx7zv7/2/

The result is IE having approx 1.6 GB in memory (tha value is almost the same for every crash on the same computer), and JS error like this: "Not enough space to complete the operation."

**Comment by alvinlindstam** [comment]
I could not reproduce your memory issues on IE10. Is it only on IE11 it occurs?

What do you mean by "very fast"? How much du you have to pan around?

When using it internally, with your own tiles, how large (file size) are the tiles and how many such layers do you use?

**Comment by TomasHorvath** [comment]
•         Screencast: http://screencast.com/t/Zv1a5ZXyz
•         It seems that it happens on any fresh installed computer with Win7 64bit + IE11. We did not try to reproduce with IE10. Some of our machines (mostly developer machines) with IE11 do not have this problem, but we did not find any significant difference in IE11 config.
•         „Fast“ means in couple minutes. The memory limit (approx 1,5GB in screencast) is different for every machine but seems mostly stable on each machine.
•         We use couple layers. OSM as backdrop and some mostly transparent network tiles in 3-6 layers over it. (Check the screencast.)
•         The problém occurs both for canvas and dom renderers. Canvas happen to cause script error, dom shows image placeholders instead of tiles that were not loaded after the memory limit is reached.
•         Chrome test on the same machine is OK.

•         We can do live demo on demand!

**Comment by alvinlindstam** [comment]
Could you do the same screencast but with the jsfiddle example?

**Comment by TomasHorvath** [comment]
We created another js with our layers: http://jsfiddle.net/xpLx7zv7/9/ (the source is not authorized for some days)

With this setup, the problem occurs easily on many of our computers.

It seems, that the problem occurs only if the tile source provides 24bit PNGs. If we change the tile source to provide 8bit PNGs, it seems to be OK (8bit PNG demo is here: http://jsfiddle.net/xpLx7zv7/8/ - also check the http headers of the source, they are a bit different, but should make this difference).

**Comment by ahocevar** [comment]
I'm pretty sure the problem is related to the default size of the tile cache, which is 2048 tiles per layer/source. If you create a custom build, you can set the `ol.DEFAULT_TILE_CACHE_HIGH_WATER_MARK` define to a lower value.

**Comment by alvinlindstam** [comment]
I was thinking the same thing, but it doesn't add upp. Even with 2048*5 images saved, they would have to be quite large to consume so much memory.

I tested https://jsfiddle.net/xpLx7zv7/9/embedded/result/, using IE11 and it's memory tab. After page load:
![skarmavbild 2015-07-01 kl 15 04 35](https://cloud.githubusercontent.com/assets/1712882/8455566/f4fa6e0e-2005-11e5-8292-b9f5e3c3d2a5.png)

After a few minutes panning:
![skarmavbild 2015-07-01 kl 15 07 46](https://cloud.githubusercontent.com/assets/1712882/8455571/fee0ad5c-2005-11e5-8efe-81d71526dc18.png)

That's 800 MB of memory increase, but the network tab only showed 2916 downloaded images with a total size of 7.5 MB (most were transparent, so average filesize was 2.6 kB).

Doing roughly the same amount of panning on the same map i Chrome and using it's heap snapshot shows only around 20 MB.

**Comment by ahocevar** [comment]
Does this happen with all renderers, or just with the canvas renderer? I'd especially be interested if the same happens with the dom renderer.

**Comment by jakubbican** [comment]
Yes, as mentioned above. But the result is not "Not enough memory" JS error, but just image placeholders in the map. The memory limit seems to be very same both for DOM and CANVAS.

**Comment by jakubbican** [comment]
We set DEFAULT_TILE_CACHE_HIGH_WATER_MARK to 256 and with this setting, the problem seems to disappear on all computers I've tested so far - so it **might be** a solution for us.

Questions:
* Why some computers handle this with no problem with original value (the browsers keep their memory around 300M with no radical increase as we can see here)
* Should the value be adjusted even more if we increase the number of layers? (20 layers instead of 5 layers)

**Comment by alvinlindstam** [comment]
It seems this is not related to ol3, but to IE 11 png handling.

Take a look at http://jsfiddle.net/9hhzr3mt/1/, which loads one of your tiles ten times and saves it to a global array. I tested with 4000 tiles, and the saved array was 1GB, with each Image element at 256 kB. This is despite the fact that the downloaded png-file is less than 1 kB.

![skarmavbild 2015-07-02 kl 16 04 14](https://cloud.githubusercontent.com/assets/1712882/8479468/49b88d0e-20d8-11e5-87a6-232467696308.png)

I tried with another png (from wikipedia) http://jsfiddle.net/9hhzr3mt/2/ with the same result (original filesize 213 kB):

![skarmavbild 2015-07-02 kl 16 19 45](https://cloud.githubusercontent.com/assets/1712882/8479661/7d57787c-20d9-11e5-9cc5-3801479c6110.png)

With potentially 5 (layers) x 2048 (cached tiles) x 256 kb (used memory per tile), thats 2,5 GB of data. So unless you can produce tiles that IE 11 doesn't expand to 250 kB, I guess reducing the cache size is your best bet.

But if this is a common problem for anyone using multiple tile layers on ol3, we might have an issue with IE 11. Any ideas on how to handle it from a library point of view? I'm considering:
* setting a global cache limit, instead of a fixed limit for each layer.
* setting a lower cache limit on IE.
* making the cache size for each source configurable by the client, without custom compilation.

**Comment by jakubbican** [comment]
I can understand, why each tile gets so much memory - if it is stored in raw uncompressed form by the browser.

I can understand the cache size limit - and appreciate to be somehow configurable without custom compilation.

But still, I can't undestand, why some setups does have this problem and some not. The IE and OS version is same, HW is different. The setups without problems are usually developer workstations with MS Visual Studio and some other stuff on it. These setups just keep the memory of IE about 300MB with no extra memory consumption like presented here, and with default ol3 cache size.

**Comment by fredj** [comment]
You can now cahnge the size of the cache, see #4805
