### ISSUE TITLE
ol.source.XYZ doesn't have a getUrls function

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#3886]

**Comment by ahocevar** [comment]
With `ol.source.XYZ`, it is not guaranteed that a url is set. Users can configure a `tileUrlFunction` instead. In such cases, `#getUrls()` should simply return `null`.

On a side note: I don’t know your use case, but I would suggest calling the `tileUrlFunction` with a specific tile coordinate to get the url, instead of using `#getUrls()`.

**Comment by bartvde** [comment]
I'm trying to remember my use case ;-) I should have put more detail in the ticket description

**Comment by bartvde** [comment]
I was likely creating a unit test for https://github.com/boundlessgeo/ole/blob/master/src/LayerGenerator.js#L100:L107 similar to: https://github.com/boundlessgeo/ole/blob/3423e642a7071cface7d9217c3e30879858f651d/test/spec/LayerGenerator.test.js#L43

**Comment by ahocevar** [comment]
Fixed with #4015.
