### ISSUE TITLE
Modify "modifystart" event emitted too late?

### ISSUE THREAD

**Issue by alvinlindstam** [openlayers/ol3#4022]
I would expect the modifystart event to be emittet before the modify interaction changes the geometry. See http://jsfiddle.net/ntd68f4L/2/

It seems that the modify interaction emits the event after a new vertex is added (if clicking between vertices).

I can get a PR done to move https://github.com/openlayers/ol3/blob/master/src/ol/interaction/modifyinteraction.js#L532 up a few lines and some tests, but would like to confirm the expected behaviour.

**Comment by alvinlindstam** [comment]
@elemoine and @bjornharrtell might be interested?

**Comment by probins** [comment]
I raised this at https://github.com/openlayers/ol3/pull/3461#issuecomment-118528219 but haven't had time to pursue.

ISTM all the use cases (add/move/delete of vertex) need reviewing; possibly an additional beforedrag event is needed for the move case.

**Comment by bjornharrtell** [comment]
I have only used `modifyend` as of yet. I added `modifystart` in #3461 for "completeness" but I probably shouldn't have as it doesn't seem to be useful at all in this state.

**Comment by alvinlindstam** [comment]
`modifystart` could be really useful, especially for undo implementations. I'll probably find a time for a PR fixing the event order soon.

Adding new events seem out of scope for this. Or do you have any suggestions as to what and how, @probins?

**Comment by probins** [comment]
like @bjornharrtell I have so far only used modifyend. Though as I said in #3461, I noticed when checking it out that modifyend is dispatched too soon when deleting a vertex - so that maybe needs moving too. I suppose it really depends on what use-cases people have. I've no problem with restricting a PR to modifystart for the moment, though the subject will probably need revisiting at some point. As with my comments on splitting, deleting a vertex also requires returning the vertex in the event; at the moment there's no way of knowing which vertex has been deleted other than comparing the before/after feature. :-(

**Comment by probins** [comment]
> I suppose it really depends on what use-cases people have

one way of demoing this would be to have examples for the different actions/events
