### ISSUE TITLE
OpenLayer 3 Scale and map extent issue

### ISSUE THREAD

**Issue by yatenj** [openlayers/ol3#4029]
Hi,
I am facing few issues with OL3.
For my View I have added 
     projection :  ol.proj.get('EPSG:27700'),

1. Scale bar is not displaying correct scale values. attaching scale bar
it shows 1000000 KM in scale line

added scale lin control as follows.
var scaleLineControl = new ol.control.ScaleLine();
	    map.addControl(scaleLineControl);
When I keep projection as default it gives proper scale line.
How to achive correct scale line for other projections?

2. When I am trying to get the extent of map 
I am getting array like

0: 308474.77874104853
1: 651146.8752803165
2: "309075.45600.6712589514647"
3: "651328.21181.334719683461"

my code is 
map.getView().setCenter([309075.45, 651328.21]);
map.getView().setZoom(17);

map.on('moveend', onMoveEnd); // in other .js file
function onMoveEnd()
{
  var mapExt = map.getView().calculateExtent(map.getSize());
}

one more thing above code is hitting   map.on() function 3 times.
so I get same mapExt (array) 3 times.

2: "309075.45600.6712589514647"
3: "651328.21181.334719683461"

I am not able to understand these max X/Y values.
both looks like string. both have 2 '.' 

Can some one help please.

**Comment by ahocevar** [comment]
Ad 1:
The scale bar will only work if you have transforms for your projection defined. Are you using proj4js and a proper definition for EPSG:27700?

Ad 2:
Looks like you somewhere provide a string where a number is needed (maybe an extent or a center). In addition, maybe you do `ol.proj.transform(extent, ...)` somewhere, instead of `ol.proj.transformExtent(extent, ...)`.

But this is definitely something with your application code. It would be easier to help if you had a JSFiddle that shows the problem.

I am closing this issue, but feel free to continue the discussion here. Next time, you may want to consider using http://stackoverflow.com/questions/tagged/openlayers-3 for questions.

**Comment by yatenj** [comment]
Hi ahocevar,
Thanks for help.
For Ad1, When I used EPSG:27700 from Proj4js scale function works fine.
But same time my wms layers (on Geoserver) are not visible anymore.
After loading map, Layer names are visible in Layer Switcher.
I am just adding my Layer as follows 

var myLayer = new ol.layer.Tile({
	          title : 'Area',
		  preload: Infinity,
		  visible: true,
		  source: new ol.source.TileWMS(({
		    url: 'http://localhost:8080/geoserver/MyProject/wms?',
		    params: {'LAYERS': 'myproject:Poly_AREA'},
		      serverType:'geoserver',
                     projection : ol.proj.get('EPSG:27700')
		       }))
		  });

In GeoServer Poly_AREA is having EPSG:27700 projection.
can you please help on this.

Please note:
When I use below custom projection Poly_AREA and other layers are visible on map but no proper scale

 var projection = new ol.proj.Projection({
		code : 'EPSG:27700',
		units : 'm'
	});
	ol.proj.addProjection(projection);

For Ad2:
I have converted X/Y values in Number.
It worked fine. 
Thanks

**Comment by ahocevar** [comment]
Keep using proj4js, and make sure that your `ol.View` is also configured with `projection: 'EPSG:27700'`.

**Comment by yatenj** [comment]
Thanks ahocevar,
proj4js was missing in my demo. 
after adding this file everything working fine.
