### ISSUE TITLE
SVG sprites don't work in IE11

### ISSUE THREAD

**Issue by alexpir** [openlayers/ol3#4090]
OL 3.8.2
The sprite (inline SVG image) generates exception in File: ol-debug.js, Line: 59315, Column: 11 when called from IE11, no problem sin Chrome.

Details: 
The referenced line is "context.drawImage(image, originX, originY, width, height,..."
Looks like either sizes or origin aren't defined despite of the following lines in the code:

function getSVGIcon() {
   var DOMURL = window.URL || window.webkitURL || window;
   var img = new Image(20, 20);
   var svg = new Blob([ICON_RECT90()], { type: 'image/svg+xml;charset=utf-8' });
   img.src = DOMURL.createObjectURL(svg);
   return img;
}
...

var iconStyle = new ol.style.Style({
                    image: new ol.style.Icon({
                        anchor: [10, 10],
                        origin: [0, 0],
                        anchorXUnits: 'pixels',
                        anchorYUnits: 'pixels',
                        rotateWithView: true,
                        img: getSVGIcon(),
                        imgSize: [20, 20],
                    })
                });
iconFeature.setStyle(iconStyle);
MAP.getLayers().item(0).getSource().addFeatures([iconFeature]);

**Comment by spatialillusions** [comment]
I think the problem is that IE11 can't tell the difference between "safe" and "unsafe" SVG code. Not sure if this can be solved with the Canvas renderer. 
http://svgopen.org/2010/papers/62-From_SVG_to_Canvas_and_Back/#security_issues

**Comment by DavidHequet** [comment]
I confirm, IE11 can't use SVG code.
OL3's Canvas renderer can render SVG if you encode it as base64 string. But you will have security error (only in IE) if you use interraction like foreachfeatureatpixel..

**Comment by spatialillusions** [comment]
Exactly my exprience, have a working example with inline SVG icons here http://spatialillusions.com/milsymbol/examples/openlayers3/imageicons.html and it works fine in IE11. But if you try to add drag interactions you will get a security warning in IE, but it will work fine in Chrome.

**Comment by spatialillusions** [comment]
@alexpir @DavidHequet I found how to fix this and sent a pull request, hopefully it will be merged to the master. If you want to get it working you just have to add one line and move one. (and make sure that your imageSize is set to two integers and not floats.)

**Comment by spatialillusions** [comment]
I rebased the pull and created a new one #4164 . Hopefully it will be accepted, I have a bunch of developers of military systems waiting for this.

**Comment by alexpir** [comment]
Thank you for the help. However I discovered that the problem is deeper than looked initially: firstly as correctly suggested there is cross-domain security issue in IE (the solution seems to be simply give up on limited interactivity as in Edge it works fine), secondly and more importantly there are some problems in drawing inline SVG onto canvas completely destroying the picture... what's bad that the second is eqally applicable to IE and FF.

I managed to reproduce the second issue not only with my site but also with http://spatialillusions.com/milsymbol/examples/openlayers3/imageicons.html  and tend to believe that the problem is generic. The trick to reproduce it to zoom in /shift area in the very begining (while data is still loading) so that all icons are outside of the viewport (OL3 seems to not load images for features outside of the viewport). Later when you scroll those icons into the viewport the the browser tries to acess images and failes (silently - there is nothing in console) the picture falls apart... looks terrible.

So, my solution was to give up in IE and FF, detect them at initial load (bad practice but stilll) and use pre-fenerated static PNGs for those browsers.,For the rest of browsers continue to use SVGs. Using PNGs I loose the ability to dynamically change the icon (my icon need to depend on "speed" parameter and should change the length of an arrow depending on it) but at least it is stable.

Would be nice if there is better way to solve the issue and stay with SVGs regardless the browser...

**Comment by spatialillusions** [comment]
Can you create a jsfiddle to trigger this behavior? (Or modify my test case http://jsfiddle.net/spatialillusions/5jx0dzpu/ ) maybe I can try to isolate the issue then.

**Comment by spatialillusions** [comment]
I changed a Math.ceil to a Math.floor and got everything working in Firefox, don't have a IE computer to test with at home. Here is an updated example with drag interactions on all icons. Works without any problems in Firefox for me. http://spatialillusions.com/milsymbol/examples/openlayers3/imageicons_with_interactions.html

**Comment by DavidHequet** [comment]
I, i tried with IE 11 at works, it don't event load the map, error here:

ol.render.canvas.Replay.prototype.replay_ = function(
....
 context.drawImage(image, originX, originY, width, height,
              x, y, width * pixelRatio, height * pixelRatio);



The error in french is "Demande d'accès à la méthode ou aux propriétés inattendue" , a think it's
"Unexpected call to method or property access."

**Comment by spatialillusions** [comment]
Make sure to round down your svg's size to whole pixels:
imgSize: [Math.floor(mysymbol.width), Math.floor(mysymbol.height)]

I had the same problem as you, but this solved it. Then the question is if it should be up to the user to round the pixels or if openlayers should do it.

**Comment by DavidHequet** [comment]
I just opened youre sample ( http://spatialillusions.com/milsymbol/examples/openlayers3/imageicons_with_interactions.html ) with IE, didn't try anithing else

**Comment by spatialillusions** [comment]
Found the cause of this, will update the code later today. It's because of my use of style functions, and you can get around that, but I will have to investigate further if it can be fixed in openlayers. (Send me an email if you want direct contact about this, you'll find my email on my homepage.)

**Comment by spatialillusions** [comment]
Now should the code be reverted back to a version that works in IE11, there is still some trouble with style functions, but I'll see if I can solve this. If you want a version using my patched open layers so you can use interactions in IE11 let me know, otherwise just wait for ol 3.10.

**Comment by spatialillusions** [comment]
I spent some time looking into this and my best guess at the moment of what is happening is that since a stylefunction is updated every time you interact with the map we will try to draw icons to the canvas before they have been generated, and then IE will throw the error because the image does not contain any data. 
https://msdn.microsoft.com/en-us/library/ff975414(v=vs.85).aspx

If we simply slow down the draw by placing the drawimage in a try catch and print the error to the console in the catch, everything will work. But I would say that you shouldn't use inline generated icons and stylefunctions together. Apply the style to the features individualy and update them when nessesary.

**Comment by ahocevar** [comment]
@spatialillusions Can I assume that this issue is related to the military icons library you are using? Should we partially revert #4164, i.e. move the drawImage call outside the try/catch block again?

**Comment by spatialillusions** [comment]
@ahocevar No keep #4164, it still solves the tainting of the canvas issue. This drawImage error is ol.render.canvas.Replay.prototype.replay_ and only happens when you are using style functions, since the style function will try to render new SVG every time you interact with the map. (Even on pan) And the error is triggered if you are using interactions or not, but not for all icons, just when open layers is trying to draw them faster than they can be created, or so it seams like.

I don't remember exactly at the moment, but I think the error I got in the drawImage in my pull was another one, and it occurred for every Icon. So by keeping the drawImage inside the try block we should be on the safe side. The errors produced by IE11 is however a bit diffuse and makes it hard to figure out exactly what the issue is. But I think in this case it is more of a security issue.

To sum everything up. 
- #4164 solves the tainting of canvas issue when using SVG icons with interactions. 
- If you are using complex inline SVG you should not use style functions, and instead attach the style to the features when they are initiated.

**Comment by ahocevar** [comment]
> •If you are using complex inline SVG you should not use style functions, and instead attach the style to the features when they are initiated.

This is where I think you're doing something wrong. Because the style function does not make a difference here. Your inline SVG images should not have a status of 'loaded' initially when you deliver them as data uri. So set them as url in the icon style, not as image. Because the latter assumes that the image is loaded already.

**Comment by spatialillusions** [comment]
@ahocevar I'll look into this and get back to you if I manage to solve it in another way. I managed to use the src and size, but did run into a lot of other IE problems, but I think I might be able to trace it.

**Comment by spatialillusions** [comment]
@ahocevar Hi, so I spent a bunch of hours trying to figure this out, and I thought that I would report my findings. 

I found a lot of strange things, like that the ol.render.canvas.Replay.prototype.replay_ is fired several times if I use a style function, and the image the drawImage with is different; not different like background map and icon, but the icon in my case was triggered several times with different values, like the standard pushpin icon from KML, my source is not KML it's GeoJSON, so strange things are happening. I also think it tired to draw the point without an icon at all, and drawImage in IE 11 will throw an error if you try to draw an image with the size [0,0] to the canvas, and this is the error we have been seeing. So, something fishy is going on there.

But the strangest part was that I did manage to draw the initial set of icons to the canvas without triggering the ol.render.canvas.Replay.prototype.replay_ and then everything worked, like the initial map worked, but as soon ol.render.canvas.Replay.prototype.replay_ was triggered things started to go wrong.

And then I tried using src and size instead of image and imgSize, but then I found that size is not passed on down to the image object in the same way as imgSize is (in one place in the code imgSize is renamed to size and this is confusing); and if you try to set imgSize when you have set src you will get an error since you arn't supposed to do that. And then you will run into trouble since IE11 has problems with finding the size of the actually loaded image if the image source isn't a url but instead a base64 encoded string.
But the strangest thing is that it works on drawing the icons before you start to interact with the map, how this is possible I still haven't been able to figure out, since it really shouldn't, since I never was able to see an icon with the correct image size assigned by the load image function.

Most of this could be solved by introducing a bunch of special solutions for solving this IE problems, like passing on the size down to the image object, but I started to see how messy my code started to look. And when I finally got it working I ended up with something where I was able to use src and size to get my map displayed with my icons, and everything looked fine until i started to interact with the map when the icons started to strobe flash all the time, since because of something the style function was triggered ALL the time, and then the map became quite useless.

So the conclusion is that we could get a better and more general solution for IE if we did a lot of recoding, introducing stuff that reduce performance in all browser except old versions of IE, and there still is a bunch of loose ends to find and figure out. Or we could say that style functions and inline generated image icons don't play well together, use the workaround that is in place in 3.10 and everything will work. (And unfortunately I'm not able to spend much more time on this, since I just had to find a solution to a specific use case, and that use case has now been solved.)

Best regards
Mån

**Comment by ahocevar** [comment]
Thanks for reporting your findings @spatialillusions. Closing this as resolved then.

**Comment by kaij** [comment]
Very interesting topic. I tested with version v3.10 (checked that above patch is included) using Style/Icon with URI src and integer size. SVG icons display correctly in IE11 as soon as size is specified, but forEachFeatureAtPixel does not work. No error messages in IE11, it just doesn't "see" the feature. 

Did I miss something in the comments - or should I open a new bug report?

**Comment by spatialillusions** [comment]
@kaij Like mentioned above, src and size will end up in some problems with the current implementation since the "image" isn't loaded from anywhere. Have a look at my jsfiddle above if you want to get it working. Before the patch interactions didn't work even if you used the workaround. 
I tried to see if it would be possible to get src and size to work, but that will require a big code rewrite and I don't know if it is worth the trouble if you can have a working workaround.

**Comment by kaij** [comment]
Thanks for the quick response! I also tried it that way, but get a "SecurityError" on every mousemove. Not just in my own code, but already at http://spatialillusions.com/milsymbol/examples/openlayers3/imageicons_with_interactions.html or http://jsfiddle.net/spatialillusions/5jx0dzpu/. Are these the right examples (which should work in IE11)?

**Comment by kaij** [comment]
@spatialillusions I checked again to match exactly your jsfiddle with OL 3.10. I think there was something wrong with my data uris before - it works now fine in IE11! Thanks!
