### ISSUE TITLE
API Documentation as docset for Dash (API Documentation Browser)

### ISSUE THREAD

**Issue by CptLausebaer** [openlayers/ol3#4206]
Hi,
it would be nice if you could provide your openlayers API documentation as a 'docset' for [dash](https://kapeli.com/dash), so developers could access and browse the documentation easier.

**Comment by tschaub** [comment]
This sounds like a nice idea.  If you can add detail to this ticket about how this would be done (given our current documentation tools), we can reopen the issue and apply the "pull request accepted" label.  As it is now, this issue is just a suggestion without enough information for someone to act on.  Closing this doesn't mean the suggestion is not appreciated, just that it is nothing that can be acted on given the level of detail that you provide.

**Comment by CptLausebaer** [comment]
Here is a guide on how to contribute your dokumentation as a docset https://kapeli.com/docsets.
There is a module for node.js to build the docset ([dash-docset-generator](https://www.npmjs.com/package/dash-docset-generator),[jsdoc-docset-generator](https://www.npmjs.com/package/jsdoc-docset-generator),...) maybe to you can implement this in your build scripts.
