### ISSUE TITLE
Performance issue with WMS layers with MAXSCALEDENOM

### ISSUE THREAD

**Issue by khamyl** [openlayers/ol3#4292]
When 8(on my PC using Chrome) layers (no matter how rich of features is it) or more are set visible, the map starts stumbling when dragging it around with mouse. Even when the MAXSCALEDENOM in server map configuration is preventing the features to be visible. So I don't see any features, but the map is already stumbling. 
Is the image already loaded to the map, even when I do not see the features becouse of MAXSCALEDENOM?
It would be nice not to load layers without features.

**Comment by ahocevar** [comment]
When your layers all come from the same WMS, it is better to use a single `ol.layer.Tile` (or `ol.layer.Image`) with a WMS source where you configure the `LAYERS` param to contain all the layers you want:
```js
new ol.source.TileWMS({
  params: {LAYERS: 'layer1,layer2,layer3'})
});
```

**Comment by khamyl** [comment]
Im doing it like that. 
But is it possible to separately control the layers? Switching on/off GetFeatureInfo etc? Anyway can you briefly explain why does it happen? Are empty images loaded to map?

**Comment by ahocevar** [comment]
OpenLayers does not know if an image is empty or not. So yes, empty images are loaded to the map. The reason why many layers slow down map interaction because layer composition is done on a canvas per-layer, and the per-layer canvases are then combined to a map canvas. So there's many pixel operations going on here.

GetFeatureInfo uses the source's LAYERS as QUERY_LAYERS, unless you configure it with your own QUERY_LAYERS. To change the layers that the source loads, use
```js
source.updateParams({LAYERS: 'layer1,layer3'});
```

**Comment by khamyl** [comment]
```
source.updateParams({LAYERS: 'layer1,layer3'});
```
If I have 10 layers in that LAYERS group and I will want to set visibility of one to hidden and I use your suggestion.. it will probably regenerate the whole image, so unchecking a checbox in my LayerSwitcher may take too long.. am I right?
