### ISSUE TITLE
WebGL style function

### ISSUE THREAD

**Issue by jfantunes** [openlayers/ol3#4381]
Hi.
I am trying to rendering a layer in webgl wich has only points. My issue here is that when I apply a style to a layer he renders me the layer in webgl if i only give an ol.style object. If i gave the style a function it renders me in canvas. I need to paint a feature based in his attributes, so for me the better way to do that is with a style function. For what i see ol3 doesn't support it for webgl or i'm missing something?

 Thank you

**Comment by tsauerwein** [comment]
Style functions are also supported by the WebGL renderer (see [here](http://jsfiddle.net/j80k0c4d/2/) for example). What makes you think that it is not supported?

> If i gave the style a function it renders me in canvas.

Note that WebGL also uses a `<canvas>` context, but instead of a [2D context](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D), the [WebGL context](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext) is used.

**Comment by jfantunes** [comment]
Yes but you are mentioning in a feature level. I was talking in a layer level, where you define a funtion of style to a layer. In that example you go feature by feature and give it a style. If you have a more generic solution, and give a style to the layer, automatically ol3 renders it in canvas

**Comment by tsauerwein** [comment]
I updated the example: http://jsfiddle.net/j80k0c4d/3/

**Comment by jfantunes** [comment]
Thank you tsauerwein, i'm going to check again whats happening with the code.

**Comment by ruirochagh** [comment]
tsauerwein, if you don't mind, in order to avail myself, I'll use this topic to make a pertinent question about my case. I've managed to render my map and some elements using webgl, but I need to make use of both canvas and webgl in my map instance since I'm trying to render polygons. 

Is there any way of achieving this without duplicating my map instances? Managing to control this in a single map would be awesome.

Best Regards

**Comment by gberaudo** [comment]
@ruirochagh, it is currently not possible to have both the Canvas 2D and WEBGL renderers active at the same time. See http://openlayers.org/en/v3.10.0/apidoc/ol.Map.html the renderer option.

There was a discussion about supporting this a long time ago: https://github.com/openlayers/ol3/issues/1084

You might also be interested to look at the experimental WEBGL polygon rendering at https://github.com/openlayers/ol3/pull/3476

**Comment by jfantunes** [comment]
Hi ruirochagh!
I needed to do a method also that change the render type based on a event and at the same time preserve the controllers, layers and interactions. I used the closure library to extend the ol3 and created a method for that. I will share my code with you.

var render=this.getRenderer();
    switch(renderType){
        case 'canvas':
            goog.dom.removeChildren(render.canvas_);
            var newRendering=ol.renderer.canvas.Map;
            this.renderer_=new newRendering(this.getViewport(),this);
            this.render();
            break;
        case 'webgl':
            goog.dom.removeChildren(render.canvas_);
            var newRendering=ol.renderer.webgl.Map;
            this.renderer_=new newRendering(this.getViewport(),this);
            this.render();
            break;

        default:
            goog.asserts.fail("Not valid render type:"+renderType);
    }

**Comment by ruirochagh** [comment]
Good evening

**Comment by ruirochagh** [comment]
Good evening,

Thank you for providing this example @jfantunes . This simplifies a huge amount of my workaround as I was also extending that same class that you're using. This covers all of my uses cases, at least for now.

@tsauerwein , thank you also for the information provided. Unfortunately, I seem to be missing some kind of import onto my example project, since no error is displayed but no polygon/line/point is drawn either, even with the correct sources loaded.

Best Regards
