### ISSUE TITLE
VectorTile - thick gap between tiles

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/ol3#4501]
Using VectorTile in 3.11 I am getting this:
![image](https://cloud.githubusercontent.com/assets/3907898/11459862/82102332-96e0-11e5-82f3-475a0d877a69.png)

http://drifted.in/other/ol/vector_tiles_gap.html
I believe my source GeoJSON files are fine (tiles were touching using TileVector in 3.10), but there is an issue in the new clipping code. That gap is visible already in the original Zoom where it is 1px. But as for higher zoom levels I have no more detailed tiles and those for maxZoom are used, that gap is scaled up to this strange result.

**Comment by ahocevar** [comment]
The problem is your tiles: they have no buffer (i.e. features are clipped at the tile border instead of having an overlap). In addition, vector tiles should be in pixel coordinates. Tiles like the ones you have here should be used with an ol.source.Vector and ol.layer.Vector. This code would work for your tiles:http://jsfiddle.net/ahocevar/ox2qyLvq/ (turn off cross origin restrictions in your browser to see the vector features).

**Comment by jan-tosovsky-cz** [comment]
Thanks a million for your example! This is exactly what I've tried to achieve. Wow.
