### ISSUE TITLE
getPixelFromCoordinate for null

### ISSUE THREAD

**Issue by mrpan** [openlayers/ol3#4506]
version v3.10.1
When I initialize the map, use the function getPixelFromCoordinate immediately,the result returns null
.
I check it ,frameState_ is still null ;
I saw the soure code used delay to set frameState_ properties:
this.animationDelay_ =
      new goog.async.AnimationDelay(this.renderFrame_, undefined, this); 

Is this a bug when use  getPixelFromCoordinate before executing this.renderFrame_? or I miss something?

**Comment by cs09g** [comment]
I've got similar problem.
Trying to use getPixelFromCoordinate after initialize the map in my code, it shows the same.
because it's not rendered all yet. so I put delay on my code with setTimout for a while then It words properly. But it's not the right way.

It looks kind of bug. too slow for setting frameState. we can't use the function if the map is not ready visually on the screen.

**Comment by ahocevar** [comment]
See https://github.com/openlayers/ol3/issues/5456#issuecomment-225125384 for a solution.
