### ISSUE TITLE
Accept a HTMLCanvasElement as img for ol.style.Icon

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol3#4513]
Currently `ol.style.Icon` requires an image element with a `src` as `img` property . With a simple change to the way we cache icons, it could also accept a `HTMLCanvasElement`. This would allow users to programmatically create icons by drawing to a canvas.

**Comment by jonataswalker** [comment]
Thanks for this feature. I'd be great.

**Comment by spatialillusions** [comment]
Would it be possible to get it to accept a SVG XML string as well? At the moment you can do a workaround and draw the SVG to a img element and use the element, but using the xml directly would be really nice.

**Comment by tschaub** [comment]
@spatialillusions you can currently use an SVG like this:

```js
var icon = new ol.style.Icon({
  src: 'http://example.com/icon.svg'
});
```

Are you programmatically generating your SVG?  I'm curious under what circumstances a URL would not be useful enough.

**Comment by spatialillusions** [comment]
Yes I'm programmatically generating my SVG. I made this library for making military symbology https://github.com/spatialillusions/milsymbol so I'm using properties from my source to generate the symbols. Since the symbols can contain a lot of information that changes frequently you reduce you network traffic a lot if you just have to update your source and render the symbols in the web browser. At the moment I solve it in open layers by requesting the svg output as a base64 encoded string, creating a img element, setting the source of the img element to my base64 string, and then creating an icon style with the img option.
I am considering adding a possibility to draw the symbols directly to the canvas, by creating draw instructions that can be drawn to svg or canvas, but it's a lot of work and it's only a hobby project.
