### ISSUE TITLE
[UX] Examples page has no link to http://openlayers.org

### ISSUE THREAD

**Issue by jnachtigall** [openlayers/ol3#4540]
Other than on the API, Tutorials, Workshop and Quick Start pages, there is no link to the Homepage from the [examples page](http://openlayers.org/en/v3.11.2/examples/). So if I want to go back from there, I have to manually retype the website into the browser's address bar.

I would propose to split off the `a.navbar-brand` into to separate links: 
* Logo and "OpenLayers 3" link to http://openlayers.org
* "Examples" link to to examples start page as it is now

**Comment by jonataswalker** [comment]
This is really missing. But IMO the [examples page](http://openlayers.org/en/v3.11.2/examples/) should repeat this node:
```html
<ul class="nav navbar-nav pull-right">
  <li><a href="/en/v3.11.2/doc">Docs</a></li>
  <li><a href="/en/v3.11.2/examples">Examples</a></li>
  <li><a href="/en/v3.11.2/apidoc">API</a></li>
  <li><a href="https://github.com/openlayers/ol3">Code</a></li>
</ul>
```

**Comment by jnachtigall** [comment]
@jonataswalker :+1: and this navbar should on all pages like this

**Comment by tschaub** [comment]
Great suggestions.

**Comment by tschaub** [comment]
Here is the template that builds the examples: https://github.com/openlayers/ol3/blob/master/config/examples/example.html

**Comment by jonataswalker** [comment]
@jnachtigall would you like to handle a pull request for this ticket?

**Comment by tschaub** [comment]
Things to consider:

 * we should use relative links (e.g. `../apidoc/` instead of `/en/vX.Y.Z/apidoc/`)
 * the links will be 404s in a development environment

I think the benefits of having a consistent header outweigh the downside of broken links in development.  Eventually, we should rework the website build to provide a consistent template for examples and other docs.  Then we could have a very simple headerless example in development.

**Comment by jnachtigall** [comment]
@jonataswalker I'd be happy if you took over, not much time currently. Thanks for asking

**Comment by marcjansen** [comment]
How could we reuse https://github.com/openlayers/openlayers.github.io/blob/build/src/theme/site.less ? would it be OK for a basic PR to just also include the generated http://openlayers.org/assets/theme/site.css ?

**Comment by jonataswalker** [comment]
To be sure what a PR for this issue would include/modify:
* add the same navigation menu (`<ul>`) to the Examples page;
  * since there's nothing special with this menu, no CSS including/modification is need;
* (not mentioned until now) include the missing `favicon.ico` in API page and Examples page.

Is that right @tschaub, @marcjansen?

> we should use relative links (e.g. ../apidoc/ instead of /en/vX.Y.Z/apidoc/)

I guess I didn't get what this means, all links are relative to `/en/vX.Y.Z/*` (`doc/tutorials/`, `apidoc/`, `examples/`). Will this modify?

**Comment by jonataswalker** [comment]
@tschaub may you give me a green light to prepare this PR? Please consider my last comment.
