### ISSUE TITLE
Release zip-s do not contain a LICENSE file

### ISSUE THREAD

**Issue by mpdaly** [openlayers/ol3#4568]
eg,

https://github.com/openlayers/ol3/releases/download/v3.12.0/v3.12.0-dist.zip

and,

https://github.com/openlayers/ol3/releases/download/v3.12.0/v3.12.0.zip

**Comment by ahocevar** [comment]
A link to the license is in the header of all JS files. Is that sufficient?

**Comment by mpdaly** [comment]
We install OL (2 currently, but are upgrading to 3) with our server, for map previews and so on. We just want to do The Right Thing which, with OL 2, was to also install the LICENSE file (and include it in our own CREDITS-type file).

We're happy to comply with whatever requirements there are.

**Comment by ahocevar** [comment]
Thanks for using OpenLayers. I am not a legal expert, but since links to the OpenLayers website and the license are included in the js binaries, all requirements should be met when you use the library as found in the distribution archives.

For reference, you can always find the license here: https://raw.githubusercontent.com/openlayers/ol3/master/LICENSE.md

**Comment by mpdaly** [comment]
Thanks for the reply. We'll carry on like that, and if anything changes then we'll catch up as and when necessary.
