### ISSUE TITLE
Tile make random copies

### ISSUE THREAD

**Issue by skyval** [openlayers/ol3#4763]
Today, after I update to the new version 3.13  there is some bug when I zoomed in or out or just slide map, Tile show random copies (ghosts) on the map. No problem with old version 3.12.1

![screenshot from 2016-02-01 17 59 12](https://cloud.githubusercontent.com/assets/12613654/12722521/f4255654-c90d-11e5-9e6c-ffd8ed39b5a7.png)

**Comment by ahocevar** [comment]
Can you provide any steps to reproduce this issue? Or maybe a hint if this can be observed with one of the examples on http://openlayers.org/en/v3.13.0/examples/ ?

**Comment by skyval** [comment]
Hi ahocevar,
Tomorrow I'll provide you hyper link to my web server with same web application but different ol3 versions (3.12.1 and 3.13).

**Comment by skyval** [comment]
OL v.3.13.0
http://track.lz-live.com/map/274

OL v.3.12.1
http://track1.lz-live.com/map/274

**Comment by ahocevar** [comment]
Thanks. Looks like the problem comes from improper handling of failed tile requests in OpenLayers. Probably a bug.

**Comment by ahocevar** [comment]
The commit that makes your application fail is 72ec3fd48d9c19461d065d23a07335341cc81f51. The reason is that your layer is not opaque. So you would have to configure the source with `opaque: false`. But this is currently not possible because of #4767.

However, since your layer is not an OSM layer at all, all you have to do is to change it's source type from `ol.source.OSM` to `ol.source.XYZ`.

**Comment by marcjansen** [comment]
And, btw, a nice application, @skyval!

**Comment by skyval** [comment]
@ahocevar I'll revise my code, many thanks. Good job! Very useful library.
@marcjansen  Oh, this is developer version and may be contain 10% from final version. We have a lot of work to do but thank you!
