### ISSUE TITLE
Error using forEachLayerAtPixel in IE

### ISSUE THREAD

**Issue by afogelberg** [openlayers/ol3#4821]
I'm experiencing problem using forEachLayerAtPixel in IE. Using forEachLayerAtPixel in Internet Explorer 9 and 10 raises SecurityError (havn't tried in 11 or Edge). The problem can be seen in the pointermove in OpenLayers example:  http://openlayers.org/en/v3.13.1/examples/getfeatureinfo-tile.html

It causes error here in ol:
`var imageData = this.context_.getImageData(
      pixelOnCanvas[0], pixelOnCanvas[1], 1, 1).data;`

**Comment by ahocevar** [comment]
Works fine in both Edge and IE11.

With IE 9 and 10 you're out of luck, because they do not support CORS for images put on a `<canvas>`. See http://stackoverflow.com/questions/16956295/ie10-and-cross-origin-resource-sharing-cors-issues-with-image-canvas.

However, if you use layer sources hosted on the same origin as your application, or proxy them to your app's origin, it will work. An alternative would be to use a vector layer.
