### ISSUE TITLE
Units tests failure

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#4848]
A test is failing but only when loaded in a browser: http://localhost:3000/test/

ol.format.GML3 / when parsing TOPP states GML / writes back features as GML 
```
TypeError: Cannot read property 'replace' of null
    at assertElementNodesEqual (test-extensions.js:156:32)
    at assertElementNodesEqual (test-extensions.js:267:11)
    at assertElementNodesEqual (test-extensions.js:267:11)
    at assertElementNodesEqual (test-extensions.js:267:11)
    at Assertion.expect.Assertion.xmleql (test-extensions.js:289:5)
    at Context.<anonymous> (loader.js/home/fredj/public_html/ol3/test/spec/ol/format/gmlformat.test.js:1037:29)


```

**Comment by fredj** [comment]
```
619e070d805a4c7e6342b1b7283f877d459a0106 is the first bad commit
commit 619e070d805a4c7e6342b1b7283f877d459a0106
Author: Tim Schaub <tim.schaub@gmail.com>
Date:   Wed Feb 3 06:43:57 2016 -0700

    Use ol.object.assign() in object.getPoperties()

:040000 040000 6de090d89c868b7f38ec5020e2ea93a8c470b06c a1c1b0851a664ad2c666e2b65d93c2c554cbaa50 M      src
```

**Comment by fredj** [comment]
The tests fails because the feature's properties are not in the right order.

**Comment by ahocevar** [comment]
Object literals in JavaScript were never guaranteed to maintain a specific order. What we are seeing now is a result of the order not being maintained. GML, however, relies on an order, because the properties of a FeatureType are an ordered `<xsd:sequence>`.

@bartvde, do you know whether this order is relevant anywhere in practice? If not, I'd suggest we add an option to `xmleq` to ignore the order of child nodes.
