### ISSUE TITLE
Overview map behavior at the beginning of the tile grid - issue with single image wms.

### ISSUE THREAD

**Issue by jakubbican** [openlayers/ol3#4982]
When at the beginning of the tilegrid (zoomlevel 0), overview map requests many tiles from the first level and shrinks the image so that it can render the map. This solution is OK for tiles (as there is no minus zoom level that would correspond to the actual zoom level of the overview map).

But when single image WMS is used, the overview map requests extra-large image from WMS and shrinks it as well. But this is not necessary as WMS can return image for any scale. The same could be applied for tiled-WMS layers in overview map which could "mimic" minus zoomlevels and request few visible tiles instead of requesting tens of tiles in different zoom level and shrinking them into the map.

**Comment by ahocevar** [comment]
@jakubbican, are you able to provide a pull request with the outlined improvements?

**Comment by jakubbican** [comment]
No sorry. 

This seems to be behavior of any map (or view), in case that current zoom is out of zoom range.

**Comment by ahocevar** [comment]
Ah ok, so that's your problem. It is a matter of the tile grid definition. For cached or static XYZ tile sets, there won't be a way around it - if your lowest tile resolution is 1000 but you render a map at 5000, you will have to request more tiles than necessary and apply oversampling.

For tiled WMS, you can always define a custom tile grid with lower resolutions. You can also pass such modified layers to `ol.control.OverviewMap`, using its `layers` config option.

For single image WMS, oversampling will only be used if you specify a `resolutions` array for the source.

To wrap this up, I think the issue you're having is merely a configuration problem. So we don't need a pull request and this ticket can be closed.

**Comment by jakubbican** [comment]
Thanks, you're right!

When we removed resolutions, the single image WMS started to work as expected - without oversampling and shrinking.
