### ISSUE TITLE
Odd tiling behaviour

### ISSUE THREAD

**Issue by vicentor** [openlayers/ol3#5099]
We tried using OpenLayers 3 for the first time for a video game map, but it seems to only render a part of the image everytime.
See this detailed post: [http://stackoverflow.com/questions/35928163/openlayers-3-static-tiles-and-xyz-coordinates](http://stackoverflow.com/questions/35928163/openlayers-3-static-tiles-and-xyz-coordinates)

Here's the [JS Fiddle](https://jsfiddle.net/magikweb/6moqu7q8/3/) for faster access.

What do you think?

**Comment by vicentor** [comment]
Here's the [JS Fiddle](JS Fiddle) for faster access.

**Comment by ahocevar** [comment]
The question is better asked on Stackoverflow, like you did already.

There is nothing wrong with OpenLayers. You are using inappropriate tools. Use `ol.source.TileImage` instead of `ol.source.XYZ`, and set its `tileGrid` appropriately by using the `ol.tilegrid.TileGrid` constructor with `resolutions` and `origin`.
