### ISSUE TITLE
ol.interaction.Draw/ol.interaction.Modify wrapX problem

### ISSUE THREAD

**Issue by sandman7920** [openlayers/ol3#5128]
ol.interaction.Modify doesn't work at all on a wrapped world

ol.interaction.Draw works partially:
if shape is drawn on none wrapped world then shape is visible on wrapped world and can be selected.
if shape is drawn on wrapped world then shape is visible and can be selected only on wrapped part of the world.

```javascript
DataExtractor.modify = new ol.interaction.Modify({
    features: DataExtractor.select.getFeatures(),
    style: DataExtractor.Styles.overlayStyle,
    pixelTolerance: 15,
    wrapX: true,
    deleteCondition : function(evt) {
        return ol.events.condition.platformModifierKeyOnly(evt) &&
                  ol.events.condition.click(evt)
    }
});

DataExtractor.select  = new ol.interaction.Select({
    style: DataExtractor.Styles.overlayStyle,
    layers: [DataExtractor.layerVector, DataExtractor.layerPolygons],
    wrapX: true,
    removeCondition: function (event) {
        return !ol.events.condition.shiftKeyOnly(event) &&
                   ol.events.condition.singleClick(event);
    },
    condition: function (event) {
        return (ol.events.condition.noModifierKeys(event) || 
                   ol.events.condition.shiftKeyOnly(event)) &&
                   ol.events.condition.click(event);
    }
});

DataExtractor.draw = new ol.interaction.Draw({
    source: DataExtractor.sourceVector,
    type: /** @type {ol.geom.GeometryType} */ (type_),
    geometryFunction: geometryFunction,
    maxPoints: maxPoints,
    wrapX: true
});
```
https://dl.dropboxusercontent.com/u/67118717/ol3_wrapX.mp4
![output](https://dl.dropboxusercontent.com/u/67118717/output_qvga.gif)

**Comment by jsalankey** [comment]
My team has been experiencing the same problem. Any feature that exists outside the longitude [-180, 180] range doesn't hit detect and also doesn't always draw correctly (it will disappear at certain zoom levels).

**Comment by ahocevar** [comment]
This behaviour is by design. Coordinates will not be wrapped by `ol.interaction.Draw` when they are drawn on a wrapped world. This is the responsibility of the application. The reason is that it is impossible for OpenLayers to guess whether you want to go around the world or just across the date line when you draw a line from 179°W to 179°E.

**Comment by matthiasdailey-ccri** [comment]
@ahocevar, I think the issue here is that after the shape is drawn, the _click area_ doesn't wrap.
When an `ol.source.Vector` has `wrapX` set to `true`, then all map clicks get their coordinates translated to the other side of the map if the click was outside -180 to 180. It happens [here](https://github.com/openlayers/ol3/blob/2bff72122757b8eeb3f3dda6191d1301ff296948/src/ol/renderer/maprenderer.js#L169) in the code.

For example, if there is a Vector shape at -190 longitude, when the user clicks on it, their click gets translated to +170 longitude. With wrapX, the shape gets drawn on the canvas at +170, but the click area does not exist at 170, only at -190. Yet, it is impossible to click at -190 because the click always gets changed to 170.

(I don't actually know how OpenLayers manages its vector click areas, so I might be wrong about that.)

**Comment by matthiasdailey-ccri** [comment]
If vectors need to be clicked or modified, it seems to me that the only solution for wrapping is to disable wrapX on `ol.source.Vector`, and wrap the features yourself in your application code by duplicating features and syncing changes between them. Any ideas?
