### ISSUE TITLE
Scale Bar and Zoom Level Incorrect in EPSG:900913

### ISSUE THREAD

**Issue by xFrieDSpuDx** [openlayers/ol3#5154]
I have two maps running, one using British national grid (EPSG:27700) and one using EPSG:900913. I use the same resolutions for both maps, but the Google mercator map appears more zoomed in. Along with this, the scale bar is different and measures only work when using geodesic measurements.

Using a scale ruler, I have confirmed that the map displayed in British national grid is correct (at least i have confirmed the scale bar and mapping is correct), while the other is always wrong. I have checked the OL3 examples page and the examples are showing the same inaccuracies.

I have noticed the inaccuracy gets greater the further North you move. When at the top of Scotland, the scale bar is ~1.8 times too large. 

Please see the attached pictures for the difference in size. Both images taken at the same zoom level and in the same location.
![googlemercator_1-10000](https://cloud.githubusercontent.com/assets/1233984/14204991/eb32a99a-f7ff-11e5-8d4a-3db7380b71b0.PNG)
![britishnationalgrid_1-10000](https://cloud.githubusercontent.com/assets/1233984/14204990/eb318240-f7ff-11e5-8150-9beddeee96ad.PNG)

**Comment by probins** [comment]
this is inevitable with Mercator's projection. Longitude distance is in 'metres' but only corresponds to metres on the ground at the equator. If you want accurate distance or area, you should not use Mercator's projection.

**Comment by ahocevar** [comment]
@xFrieDSpuDx: To me, the scale bar appears correct in both images. Note that it shows 200 m in the National Grid map, and 100 m in the Web Mercator map. Your problem seems to be the way you calculate the scale, and here @probins is right. With the way you calculate it, it is only correct at the equator, and there you would also get zoom levels that look equal for both maps (hypothetically, because National Grid won't work at the Equator). To get the correct scale at the map center, you have to use `ol.proj.Projection#getPointResolution()`:
```
var dpi = 89; // use your screen dpi here
var view = map.getView();
var projection = view.getProjection();
var resolution = projection.getPointResolution(view.getResolution(), view.getCenter());
var scale = resolution * projection.getMetersPerUnit() * dpi * 39.37;
console.log(scale);
```js
