### ISSUE TITLE
Pull Requests Required to Be Up to Date

### ISSUE THREAD

**Issue by nicholas-l** [openlayers/ol3#5161]
Further to comments in #5086 it seems that GitHub is requiring that the branch be up to date which I think is configurable (see [this](https://help.github.com/articles/about-required-status-checks/) and [this](https://github.com/blog/2137-protected-branches-improvements). Is this desirable? Doesn't it put a hindrance on the pull request process i.e. requiring a rebase anytime a pull request is needed to be merged?

**Comment by nicholas-l** [comment]
Also GitHub have now introduced the ability to [squash merges ](https://github.com/blog/2141-squash-your-commits) which might be helpful.

**Comment by ahocevar** [comment]
Thanks for creating this ticket @nicholas-l. I have disabled the requirement for a pull request branch to be up-to-date with master for now. We can revisit this any time if others think we should be less lenient.

Squash merges are also enabled for our repository. Should make life easier for first-time contributors and result in a cleaner history.

**Comment by nicholas-l** [comment]
Thanks :+1:

**Comment by probins** [comment]
for those PRs that are around for a while before being merged (because of discussions, or dependency on other pending changes, or whatever), it might be a good idea to at least rerun Travis. For example, new tests might have been added that an old PR would fail, but might not cause a merge conflict. Contributors can do this by rebasing or simply closing and reopening the PR.

**Comment by marcjansen** [comment]
I am also very happy with how it is right now! Thanks to everyone 👏
