### ISSUE TITLE
Drag-and-Drop GPX, Write Geojson

### ISSUE THREAD

**Issue by nitrag** [openlayers/ol3#5300]
When I drag and drop the attached GPX file onto my map the features load and display fine. However when I write all the features to geojson it keeps the GPX coordinates in an array of 4 which is not to GeoJSON spec. 

This GPX File:
https://gist.github.com/nitrag/91ce9dc49b3f4d375b1b72cb1d3d47d4

Produces this (bad spec) geojson:
https://gist.github.com/nitrag/5cd8038fe036e99ce4f974ccc3b68335

Relevant code:
https://gist.github.com/nitrag/9ea09935920f1af5434aa10305b71794

**Comment by nitrag** [comment]
Okay it's not just GPX, it seems that the Geojson write features is exporting in this weird format:

[lng, lat, ?, ?] 

Is this a bug? How can I get just two array points?

**Comment by tschaub** [comment]
Because `<wpt>` elements [can have](http://www.topografix.com/GPX/1/1/#type_wptType) nested `<ele>` and `<time>` elements, the GPX format creates geometries with an "XYZM" layout.  So the third and fourth values are elevation and time.  GeoJSON [allows for](http://geojson.org/geojson-spec.html#positions) more that two values associated with a position, so these values are retained when writing out the geometries originally created from the GPX file.

If you create geometries with an XY layout (e.g. `new ol.geom.Point([0, 0])`), you'll only see two values per position when serializing these geometries as GeoJSON.

**Comment by nitrag** [comment]
Ah, thank you. This makes sense I could not find any documentation. Much appreciated.
