### ISSUE TITLE
Making ol.source.Vector.loadFeatures public to enable overriding

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/ol3#5349]
In certain scenarios ( #5348 ) the custom loader is not sufficient for proper loading data as it is triggered only for unprocessed extents regardless the zoom level. Currently there is no way to override this behaviour. 

I've done some promising experiments with overriding the following method in my script, but it only works when referencing ol-debug.js:
```
ol.source.Vector.prototype.loadFeatures = function(extent, resolution, projection) {
   ...
}
```
So I suppose if this method was public, it could solve my problem. 

Thanks.

**Comment by ahocevar** [comment]
What you are trying to achieve is not the goal of a loading strategy. It is a use case for the VectorTile source.

You can work around this by clearing all features when the view resolution changes.

**Comment by jan-tosovsky-cz** [comment]
> You can work around this by clearing all features when the view resolution changes.

Yes, but it results in not very smooth transition between zoom levels - the vector content dissapear and after while it is replaced with another one.

So I basically store current features in temporary variable, loading new ones and after that delete those 'current' ones. However, as the extent cache (loadedExtentsRtree) is not cleared, not all new features are loaded (as still considered as already loaded).

The goal of my customization is clearing that extent cache.

**Comment by ahocevar** [comment]
If you clear the extent cache, then features for already loaded extents will be requested again. But they won't be added to the source because their feature ids are already there. So calling `clear()` on the source is the way to to.

As I said already, you should be using vector tiles. If that's not possible for you, you can still fully customise how features are loaded by configuring the source without url, format and loader. Then you can request features as you wish using XMLHttpRequest or fetch, parse them with ol.format.Whatever, and use the source's addFeatures method to add them.

**Comment by ahocevar** [comment]
See https://github.com/openlayers/ol3/issues/5349#issuecomment-219938901 for a solution that does not require clearing the extent cache.
