### ISSUE TITLE
dblclick event triggers click event

### ISSUE THREAD

**Issue by cs09g** [openlayers/ol3#5571]
Hi, I'm wondering that it's correct action.

1. add click event
map.on("click", function(){ console.log("click"); });

2. add dblclick event
map.on("dblclick", function(){ console.log("dblclick"); });

3. click the map
4. dblclick the map

---- console -----
click // 3
click // 4
click // 4
dblclick // 4

when i dblclick the map, it shows "click" twice then shows "dblclick"

or

1. add click event
map.on("click", function(){ console.log("click"); });

2. dblclick the map

------ console ------
click
click

**Comment by tsauerwein** [comment]
Yes, that is the expected behaviour. If you don't want to get an event for double-clicks, you can listen on "singleclick":

**click** (ol.MapBrowserEvent) - A click with no dragging. A double click will fire two of this.
**dblclick** (ol.MapBrowserEvent) - A true double click, with no dragging. 
**singleclick** (ol.MapBrowserEvent) - A true single click with no dragging and no double click. Note that this event is delayed by 250 ms to ensure that it is not a double click. 

http://openlayers.org/en/latest/apidoc/ol.Map.html
