### ISSUE TITLE
performance issue in the new version

### ISSUE THREAD

**Issue by itayod** [openlayers/ol3#5683]
I upgraded the ol version in my application and i have noticed that it caused me huge performance problems in mobile.

I have made a small video that demonstrate the problem:
in the video we are using a small application that basically upload a very simple map,
using the old ol version (3.13) and then the new version (3.17).

the link to the video:
https://www.dropbox.com/s/lq78vz6j5vou7gm/ol_new_version_issues.mp4?dl=0

**Comment by fredj** [comment]
Can you see this issue with the examples ?
 * http://openlayers.org/en/v3.13.1/examples/simple.html
 * http://openlayers.org/en/v3.17.1/examples/simple.html

**Comment by itayod** [comment]
hi,
the same issue has happened in the examples.

**Comment by ahocevar** [comment]
This is probably because your device has a device pixel ratio higher than 1, but a graphics engine that does not have enough power to handle a canvas with the screen size at that resolution. In 3.13.1, tile layers with a pixel ratio of 1 were composed into a canvas with pixel ratio 1. In 3.17.1, the tiles of such a layer are composed into the map canvas, which has a higher resolution for matching the device pixel ratio. So there are more pixels to deal with.

Go to http://mydevice.io/ with your mobile device and check the "JS pixel-ratio". It will probably be 1.5. If so, you should be able to get a performance boost by configuring your map with
```js
  pixelRatio: Math.floor(window.devicePixelRatio || 1)
```
If it still feels slow, try
```
  pixelRatio: 1
```

**Comment by itayod** [comment]
looks like it doesn't solve the problem :(
I have set the pixelRatio on the map object but the problem continue.

**Comment by ahocevar** [comment]
I'm surprised that it doesn't get better when you lower the pixel ratio, but the difference between v3.13.1 and v3.17.1 is that we use a bigger canvas when we start rotating the map. In v3.13.1, when the map is rotated about 45 degrees, the canvas size should be about the same as in v3.17.1. So with the old version, when the rotation is about 45 degrees, it should be equally slow as v3.13.1.

**Comment by ahocevar** [comment]
@itayod You may want to try #5724, which should fix the issue.
