### ISSUE TITLE
How to compute correct extent for XYZ source ?

### ISSUE THREAD

**Issue by felixveysseyre** [openlayers/ol3#5802]
Hello,

I have been building a large image viewer around _OpenLayers3_ and the _XYZ source_.

Since I know the exact image size, I would like to compute the _**layer extent**_ which allow me to display only the image content, and no white border around it.

Here is a basic JSFiddle which contains all the parameters I can work with: http://jsfiddle.net/3d7mrths/4/

**Comment by felixveysseyre** [comment]
Based on my previous JSFiddle and some advice given by OpenLayers3 developers, I have developed the following function, computing the possible correct extent and view center:
```
var computeExtentAndCenter = function(width, height) {
  var f1 = function(v){
    return Math.ceil(Math.log(v / 256) / Math.log(2));
  };

  var f2 = function(v){
    return 256 * Math.pow(2, v);
  };

  var constrainedWidth = f2(f1(width));
  var constrainedHeight = f2(f1(height));

  var fWidth = width / constrainedWidth;
  var fHeight = height / constrainedHeight;

  var extent = [
    fWidth * 0,
    fHeight * (constrainedHeight - height),
    fWidth * width,
    fHeight * constrainedHeight
  ];

  var center = [
    (extent[0] + extent[2]) / 2,
    (extent[1] + extent[3]) / 2
  ];

  return {
    extent: extent,
    center: center
  }
};
```
Here is the JSFiddle associated: http://jsfiddle.net/otbvz824/2/

<img width="498" alt="capture d ecran 2016-08-29 a 11 08 43" src="https://cloud.githubusercontent.com/assets/4909259/18046620/01fa296a-6dd9-11e6-89a4-36ee6d32a1c1.png">

As you can see there is still white content displayed.
I tried the same with another image and the result was similar.

The function I have built seems overcomplicated to me. Displaying a fixed-size-XYZ-source should not be more simple than that ?

**Comment by ahocevar** [comment]
Your guts feeling is right, it's much simpler than you think. The key to success is: you're working with an image, not with a planet that needs to be projected to an image. So you don't need a projection!

For the zoom levels, you need is the resolutions. This is easy. When you're using at the full image (i.e. at zoom level zoomMax), the resolution is 1. Multiply that by 2 as you count down your zoom levels, until you reach zoomMin:
```js
var resolutions = [];
for (var i = zoomMax; i >= zoomMin; --i) {
  resolutions.push(Math.pow(2, i));
}
```
The next thing you need to know is that the OpenLayers map coordinate system increases x from left to right and y from bottom to top. With [0, 0] in the top left corner, the, resulting extent is:
```js
var extent = [0, -height, width, 0];
```
Since ol.source.XYZ is for worlds in Web Mercator Projection, it's the wrong tool. You'll want ol.source.TileImage instead. For the required tile grid, you only need your resolutions and the origin:
```js
var source = new ol.source.TileImage({
  url: URL,
  tileGrid: new ol.tilegrid.TileGrid({
    resolutions: resolutions,
    origin: [0, 0]
  })
});
```
This all boils down to a very simple working fiddle: http://jsfiddle.net/3d7mrths/5/.

**Comment by felixveysseyre** [comment]
Thanks a lot @ahocevar, It works perfectly fine !
