### ISSUE TITLE
ol.proj.toLonLat breaks when passing strings(sometimes?)

### ISSUE THREAD

**Issue by fredlllll** [openlayers/ol3#6111]
okay so i was working on an app, and had to switch my webservice, that supplies coordinates from my dev environment to a test environment. test environment uses a slightly older version of mysql/mariadb and returns all results as strings, even though they are numbers, while dev does not. im then using these values in php, put them in an object, and return the json representation of that. so for dev, i get [number,number] in my app, and for test i get [string,string]. testing this in the console did not give me an error, but strangely in code it does mess up the latitude (after reconversion 48... to -41 and 1 to -108) when converting from lonlat.

as testcase i tried this in the console, but it worked as expected (these were the exact values that got screwed up)

ol.proj.fromLonLat(ol.proj.toLonLat([11.56202446466,48.141754842565]))
ol.proj.fromLonLat(ol.proj.toLonLat(["11.56202446466","48.141754842565"]))

i know coordinate is supposed to be a number[], but thanks to dynamic typing, javascript doesnt care for anything. does anyone else think it might be a good idea to add typechecks to some methods and throw errors if the wrong type is put in?

**Comment by tschaub** [comment]
Thanks for the suggestion, but I think that at this time we are not going to put runtime type checks in places like this.

**Comment by TDesjardins** [comment]
Hello Tim,

do you have a special reason for not doing this? In my opinion you could save a lot of time (yours and from users of ol3) when checking types. Have a look at these issues:

https://github.com/openlayers/ol3/issues/6086
https://github.com/openlayers/ol3/issues/6016

The cause is always the same and I am sure that these issues are not the last ones.

This is only a recommendation. For me this is not a problem because I use typesafe https://github.com/TDesjardins/gwt-ol3

Best regards

Tino
