### ISSUE TITLE
View not updated after map rotation

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol3#6118]
This is a regression caused by e447df39f7a8929026185d4f6c4d7bee24b2685d, which can easily be reproduced with the simple.html example:

1. Open simple.html in your browser
2. Rotate the map
3. See tiles not being rendered in the corners of the map
4. Click on the map, and tiles are immediately rendered

This gif shows steps 1-3:
![nov-13-2016 10-53-16](https://cloud.githubusercontent.com/assets/211514/20244811/9e535bb4-a98f-11e6-8c3d-4a3b3f809258.gif)

**Comment by ahocevar** [comment]
@tschaub, any idea how this could be fixed?

**Comment by tschaub** [comment]
This happens because nothing about the view "changes" after we [decrement the interacting hint](https://github.com/openlayers/ol3/blob/master/src/ol/interaction/dragrotate.js#L95-L98) in `pointerup`.

One alternative is to always call `view.changed()` in cases like this.  For this to work, we also need the map to re-render on view `CHANGE` (it only re-renders on `PROPERTYCHANGE` right now).  See #6120 for a change along these lines.

What you're seeing is a symptom of the same problem we have seen when trying to remove the apparently unnecessary `map.render()` calls scattered around.  Changing a view "hint" should *always* result in a re-render - but it doesn't currently, so we force it in other ways.

It probably makes sense to make `view.setHint()` fire `CHANGE` (in addition to having `map.render()` called on `CHANGE`).  This would make it so we cannot go from interacting to not interacting (or animating to not animating) without loading tiles or anything else that might be done conditionally post-render.

**Comment by tschaub** [comment]
See #6121 for a proposal to have `view.setHint()` trigger `CHANGE`.
